### ISSUE TITLE
Eigene GitHub-Orga

### ISSUE THREAD

**Issue by Krzmbrzl** [pmayd/OPT-Mod#3]
Die OPT Repos sollten nicht auf James' privatem Acc liegen, sondern in einer extra OPT-Orga. Damit ist das Ganze besser abgesichert für die Zukunft und auch die Rechteverwaltung sollte einfacher sein...

**Comment by Krzmbrzl** [comment]
Ich war mal so frei und hab das gemacht. Alle, die als Watcher hier bei dem Repo sind, sind als Mitglieder eingeladen.

**Comment by pmayd** [comment]
Hm... Sowas wäre vielleicht mit mir abzusprechen gewesen?

**Comment by Krzmbrzl** [comment]
Da die Repos hier sowieso nocj leer sind und niemand angefangen hat daran was zu machen, hat es ja niemandem geschadet.
Und da du nicht geantwortet hast, ich es aber für das Erstellen des Grundgerüsts gebraucht habe, hab ich das halt einfach gemacht.

Und groß ändern tut sich ja nichts. Das Repo sieht gleich aus, gleiche Lizenz, etc. Und du hast nach wie vor alle Admin-Rechte daran (kannst mich da als Admin auch wieder entfernen, wenn du willst). Deswegen dachte ich, das sei kein Problem

**Comment by pmayd** [comment]
Passt schon, ich reagiere empfindlich bei solch "rechtlichen" Fragen wie jemand, der mal eben ein neues repository für die Gruppe aufsetzt. Aber das gehört hier nicht her und in der Tat hat es niemandem geschadet, ich begrüße deine Initiative und auch deine Erfahrung bzw. Fähigkeiten, nur eben vom Ablauf unglücklich, auch wenn es nur um ein simples "machen wir so" ging ;)

**Comment by Krzmbrzl** [comment]
Alles klar - werd ich mir für die Zukunft merken :+1:
